### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by ginomessmer** [BerkanYildiz/Cachet.NET#1]
I love the idea of this library and I consider to use it. Any plans on a possible NuGet package hosted on [nuget.org](https://www.nuget.org/)?

**Comment by NizZ8** [comment]
I was looking for this as well. i temporarily packaged it for my own use/testing here - https://www.nuget.org/packages/Cachet.NET/1.0.0 .  

I just followed this guide here to build it: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio

I can take down the one i pushed up if the source owner wants to publish/manage it.

**Comment by BerkanYildiz** [comment]
Hi @NizZ8,

I'd like to have the ownership transferred so I can update the nuget package.

Package Settings ->

![image](https://user-images.githubusercontent.com/15068742/52664152-96eeff80-2f08-11e9-8ffe-aab836887cb5.png)

Thank you.

**Comment by NizZ8** [comment]
Sorry didn't see this request until now, submitted your alias for ownership.  Feel free to remove me once you have control of it.
