### ISSUE TITLE
CloudFlare Forbidden

### ISSUE THREAD

**Issue by Zyphrono** [BerkanYildiz/Cachet.NET#5]
I keep getting a CloudFlare Forbidden error while getting API data from status.vrchat.com.

Weirdly I can still connect using CURL and just by typing it in the search bar.

I already tried to assign a different user-agent with no luck.
Any fixes for this?

If this repository is still getting maintained ofcourse.

**Comment by BerkanYildiz** [comment]
No idea. You can temporarily add a rule in your Cloudflare Dashboard to disable filtering requests on /api/* or whatever your API is routed at.

**Comment by Zyphrono** [comment]
> No idea. You can temporarily add a rule in your Cloudflare Dashboard to disable filtering requests on /api/* or whatever your API is routed at.

That's going to be a problem as it's not my API ;)

**Comment by BerkanYildiz** [comment]
Could show the code that's failing and how you're initializing the instance ?

**Comment by Zyphrono** [comment]
![image](https://user-images.githubusercontent.com/22412324/117169376-5752ad80-adc9-11eb-8452-6ca91cebd1c9.png)
> Could show the code that's failing and how you're initializing the instance ?

I used this code with the demo of Cachet and that worked.

**Comment by Zyphrono** [comment]
This does work for some reason.
![image](https://user-images.githubusercontent.com/22412324/117180729-c84b9280-add4-11eb-9659-62d1502a9f1d.png)
Status code: 200

**Comment by Zyphrono** [comment]
Already found a workaround by using another library.
